using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using VienHoa.IService;
using VienHoa.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using VienHoa.View.NguyenNhienLieuView;
using VienHoa.View.NhienLieuView;
using VienHoa.View.DuAnView;
using DevExpress.XtraSplashScreen;
using VienHoa.Entity;
using VienHoa.DataEx;
using Microsoft.Office.Interop.Excel;

namespace VienHoa.View
{
    public partial class Form1 : DevExpress.XtraBars.Ribbon.RibbonForm
    {

        private readonly INguyenLieuSanPhamChiSoTacDong nguyenLieuSanPhamChiSoTacDong;
        private readonly INhienLieuSanPhamChiSoTacDong nhienLieuSanPhamChiSoTacDong;
        private readonly ITinhThaiDauRa tinhThaiDauRa;
        private readonly IAxitHoa tinhAxithoa;
        private readonly IChiSoKhac chiSoKhac;
        public Form1()
        {
            nhienLieuSanPhamChiSoTacDong = new NhienLieuSanPhamChiSoTacDongService();
            nguyenLieuSanPhamChiSoTacDong = new NguyenLieuSanPhamChiSoTacDongService();
            tinhThaiDauRa = new TinhThaiDauRa();
            tinhAxithoa = new AxitHoaService();
            chiSoKhac = new CacChiSoKhac();
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
            ribbonControl1.SelectedPageChanged += ribbonControl1_SelectedPageChanged;
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {


        }

        private void gridSplitContainer1Grid_Click(object sender, EventArgs e)
        {

        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
        }

        private void btnLoaiChatThai_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            currentForm = new LoaiChatThaiView(tblMain);
        }

        private void btnChatThai_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            currentForm = new ChatThaiView(tblMain);
        }



        private void btnThaiDauRa_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            currentForm = new ThaiDauRaView(tblMain);
        }

        private void btnSanPham_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            currentForm = new SanPhamView(tblMain);
        }

        private void btnDoanhNghiep_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            currentForm = new QLDoanhNghiep(tblMain);
        }

        private void btnThemDuLieu_Click(object sender, EventArgs e)
        {
            if (currentForm != null)
            {
                switch (currentForm.Name)
                {
                    case "SanPhamView":
                        FormSanPhamFluent formFluent = new FormSanPhamFluent();
                        formFluent.ShowDialog();
                        new SanPhamView(tblMain);
                        break;
                    case "GayNongLenToanCauView":
                        new GayNongLenToanCauFluentForm().ShowDialog();
                        new GayNongLenToanCauView(tblMain);
                        break;
                    case "HeSoPhatThaiDienView":
                        new HeSoPhatThaiDienFluentForm().ShowDialog();
                        new HeSoPhatThaiDienView(tblMain);
                        break;
                    case "ChatThaiView":
                        new ChatThaiFluentForm().ShowDialog();
                        new ChatThaiView(tblMain);
                        break;
                    case "LoaiChatThaiView":
                        new LoaiChatThaiFluentForm().ShowDialog();
                        new LoaiChatThaiView(tblMain);
                        break;
                    case "ThaiDauRaView":
                        new ThaiDauRaFluentForm().ShowDialog();
                        new ThaiDauRaView(tblMain);
                        break;
                    case "fmNguyenLieu":
                        NguyenLieuFluent fm = new NguyenLieuFluent();
                        fm.ShowDialog();
                        new fmNguyenLieu(tblMain);
                        break;
                    case "fmNhienLieu":
                        NhienLieuFluent fm1 = new NhienLieuFluent();
                        fm1.ShowDialog();
                        new fmNhienLieu(tblMain);
                        break;
                    case "QLDoanhNghiep":
                        new FormFluentThemDoanhNghiep().ShowDialog();
                        new QLDoanhNghiep(tblMain);
                        break;
                    case "NhaMayView_Modified":
                        new InforAddHub().ShowDialog();
                        new NhaMayView_Modified().Reload_data(tblMain);
                        break;
                    case "FormDuAnView":
                        FormDuAnFluent formDuAnFluent = new FormDuAnFluent();
                        formDuAnFluent.ShowDialog();
                        new FormDuAnView(tblMain);
                        break;
                    default:
                        break;
                }
            }
        }

        private void btnGayNongLenToanCau_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            currentForm = new GayNongLenToanCauView(tblMain);
        }


        private void btnHeSoPhatThaiDien_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            currentForm = new HeSoPhatThaiDienView(tblMain);
        }
        private Form currentForm;


        private void btnNhienLieu_ItemClick_1(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            currentForm = new fmNhienLieu(tblMain);
        }

        private void btnNguyenLieu_ItemClick_1(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            currentForm = new fmNguyenLieu(tblMain);
        }

        private void btnNhaMay_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            currentForm = new NhaMayView_Modified(tblMain);
        }

        private void barButtonItem3_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            currentForm = new SanPhamView(tblMain, "TinhToan");
        }

        private void ribbonControl1_SelectedPageChanged(object sender, EventArgs e)
        {
            if (ribbonControl1.SelectedPage == ribbonPage1)
            {
                btnThemDuLieu.Visible = true;
                btnImport.Visible = false;
                currentForm = new SanPhamView(tblMain);
            }
            else if (ribbonControl1.SelectedPage == ribbonPage2)
            {
                btnThemDuLieu.Visible = false;
                btnImport.Visible = true;
                currentForm = new SanPhamView(tblMain, "TinhToan");
            }
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            currentForm = new SanPhamView(tblMain);
        }

        private void btnDuAn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            currentForm = new FormDuAnView(tblMain);
        }

        private void btnImport_Click(object sender, EventArgs e)
        {
            OpenFileDialog openFileDialog = new OpenFileDialog
            {
                Filter = "Excel Files|*.xls;*.xlsx;*.xlsm",
                Title = "Select an Excel File"
            };

            if (openFileDialog.ShowDialog() == DialogResult.OK)
            {
                SplashScreenManager.ShowDefaultWaitForm("Đang xử lý", "Vui lòng chờ...");
                string filePath = openFileDialog.FileName;
                Microsoft.Office.Interop.Excel.Application xlApp = new Microsoft.Office.Interop.Excel.Application();
                Workbook xlWorkbook = xlApp.Workbooks.Open(filePath);
                _Worksheet xlWorksheet = xlWorkbook.Sheets[1];
                Microsoft.Office.Interop.Excel.Range xlRange = xlWorksheet.UsedRange;


                string congNghe = xlRange.Cells[8, 8].Value2.ToString();
                string tenSanPham = xlRange.Cells[9, 8].Value2.ToString();

                using (var context = new AppDbContext())
                {
                    using (var dbTran = context.Database.BeginTransaction())
                    {
                        try
                        {
                            // Công suất thiết kế
                            string donViCongSuat = xlRange.Cells[10, 6].Value2.ToString();
                            double congSuatThietKe = xlRange.Cells[10, 8].Value2;
                            CongSuatThietKe newCongSuatThietKe = context.congSuatThietKes.SingleOrDefault(x => x.DonViCongSuat == donViCongSuat && x.CongSuatDinhMuc == congSuatThietKe);
                            if (newCongSuatThietKe == null)
                            {
                                newCongSuatThietKe = new CongSuatThietKe
                                {
                                    DonViCongSuat = donViCongSuat,
                                    CongSuatDinhMuc = congSuatThietKe,
                                };
                                context.congSuatThietKes.Add(newCongSuatThietKe);
                                context.SaveChanges();
                            }
                            int congSuatThietKeId = newCongSuatThietKe.Id;

                            // Doanh nghiệp
                            string tenDoanhNghiep = xlRange.Cells[7, 8].Value2.ToString();
                            DoanhNghiep newDoanhNghiep = context.doanhNghieps.SingleOrDefault(x => x.TenCongTy == tenDoanhNghiep);
                            if (newDoanhNghiep == null)
                            {
                                newDoanhNghiep = new DoanhNghiep
                                {
                                    TenCongTy = tenDoanhNghiep,
                                };
                                context.doanhNghieps.Add(newDoanhNghiep);
                                context.SaveChanges();
                            }
                            int doanhNghiepID = newDoanhNghiep.Id;

                            // Loại nhà máy
                            string loaiNhaMay = xlRange.Cells[11, 8].Value2.ToString();
                            LoaiNhaMay newLoaiNhaMay = context.loaiNhaMays.SingleOrDefault(x => x.TenLoai == loaiNhaMay);
                            if (newLoaiNhaMay == null)
                            {
                                newLoaiNhaMay = new LoaiNhaMay
                                {
                                    TenLoai = loaiNhaMay,
                                };
                                context.loaiNhaMays.Add(newLoaiNhaMay);
                                context.SaveChanges();
                            }
                            int loaiNhaMayID = newLoaiNhaMay.Id;

                            // Loại lò nung
                            string loaiLoNung = xlRange.Cells[6, 6].Value2.ToString();
                            LoaiLoNung newLoaiLoNung = context.loaiLoNungs.SingleOrDefault(x => x.TenLoaiLo == loaiLoNung);
                            if (newLoaiLoNung == null)
                            {
                                newLoaiLoNung = new LoaiLoNung
                                {
                                    TenLoaiLo = loaiLoNung,
                                };
                                context.loaiLoNungs.Add(newLoaiLoNung);
                                context.SaveChanges();
                            }
                            int loaiLoNungID = newLoaiLoNung.Id;

                            // nhà máy
                            string tennhamayValue = xlRange.Cells[6, 8].Value2.ToString();
                            NhaMay newNhaMay = context.nhaMays.SingleOrDefault(x => x.TenNhaMay == tennhamayValue && x.CongSuatThietKeId == congSuatThietKeId && x.DoanhNghiepId == doanhNghiepID
                            && x.LoaiNhaMayId == loaiNhaMayID && x.LoaiLoNungId == loaiLoNungID);
                            if (newNhaMay == null)
                            {
                                newNhaMay = new NhaMay
                                {
                                    TenNhaMay = tennhamayValue,
                                    CongSuatThietKeId = congSuatThietKeId,
                                    DoanhNghiepId = doanhNghiepID,
                                    LoaiNhaMayId = loaiNhaMayID,
                                    LoaiLoNungId = loaiLoNungID,
                                };
                                context.nhaMays.Add(newNhaMay);
                                context.SaveChanges();
                            }
                            int nhaMayID = newNhaMay.Id;

                            // dự án
                            string tenDuAn = xlRange.Cells[8, 6].Value2.ToString();
                            DuAn duAn = context.duAns.SingleOrDefault(x => x.TenDuAn == tenDuAn && x.DoanhNghiepId == doanhNghiepID);
                            if (duAn == null)
                            {
                                duAn = new DuAn
                                {
                                    TenDuAn = tenDuAn,
                                    DoanhNghiepId = doanhNghiepID,
                                };
                                context.duAns.Add(duAn);
                                context.SaveChanges();
                            }
                            int duAnID = duAn.Id;

                            // Sản phẩm
                            SanPham newSanPham = new SanPham
                            {
                                CongNghe = congNghe,
                                TenSanPham = tenSanPham,
                                NhaMayId = nhaMayID,
                                DuAnId = duAnID,
                                LoaiLoNungId = loaiLoNungID,
                            };
                            context.sanPhams.Add(newSanPham);
                            context.SaveChanges();
                            int idSanPham = newSanPham.Id;

                            //nguyên liệu sản phảm
                            List<int> tenNguyenLieu = new List<int>();
                            int specialColumnForNames = 5;
                            for (int row = 22; row <= 26; row++)
                            {
                                string value = xlRange.Cells[row, specialColumnForNames].Value2.ToString();
                                int idvalue = context.nguyenLieus.FirstOrDefault(x => x.TenNguyenLieu == value)?.Id ?? 0;
                                tenNguyenLieu.Add(idvalue);
                            }

                            // Thực hiện thêm nguyên liệu sản phẩm các giai đoạn
                            int startColumnNLN = 9;
                            int endColumnNLN = 24;
                            int startRowNLN = 22;
                            int endRowNLN = 26;

                            List<int> LstNguyenLieu = new List<int>();

                            for (int row = startRowNLN; row <= endRowNLN; row++)
                            {
                                string nameNL = xlRange.Cells[row, 5].Value2.ToString();
                                NguyenLieu NLSP = context.nguyenLieus.SingleOrDefault(x => x.TenNguyenLieu == nameNL);
                                for (int col = startColumnNLN; col <= endColumnNLN; col++)
                                {
                                    double cellValue = xlRange.Cells[row, col].Value2 != null ? (double)xlRange.Cells[row, col].Value2 : 0;
                                    string nameLCA = xlRange.Cells[21, col].Value2.ToString();
                                    int lcaId = context.LCAs.SingleOrDefault(x => x.KyHieu == nameLCA).Id;
                                    if (cellValue != 0)
                                    {
                                        NguyenLieuSanPham nguyenLieuSanPham = new NguyenLieuSanPham();
                                        nguyenLieuSanPham.SoLuong = cellValue;
                                        nguyenLieuSanPham.SanPhamId = idSanPham;
                                        nguyenLieuSanPham.LCAId = lcaId;
                                        nguyenLieuSanPham.NguyenLieuId = NLSP.Id;
                                        nguyenLieuSanPham.DonViId = 1;
                                        context.nguyenLieuSanPhams.Add(nguyenLieuSanPham);
                                        context.SaveChanges();
                                        LstNguyenLieu.Add(nguyenLieuSanPham.Id);
                                    }
                                }
                            }




                            //Tiêu thụ điện năng 
                            int startDien = 9;
                            int endColumnDien = 24;
                            int startRowDien = 41;
                            int endRowDien = 44;

                            List<NhienLieuSanPham> TaoNangLuong = new List<NhienLieuSanPham>();
                            for (int row = startRowDien; row <= endRowDien; row++)
                            {
                                string nameNhienLieu = xlRange.Cells[row, 5].Value2.ToString();
                                NhienLieu NLSP = context.nhienLieus.SingleOrDefault(x => x.TenHienThiTieuThu.ToLower() == nameNhienLieu.ToLower());
                                for (int col = startDien; col <= endColumnDien; col++)
                                {
                                    double cellValue = xlRange.Cells[row, col].Value2 != null ? (double)xlRange.Cells[row, col].Value2 : 0;
                                    string nameLCA = xlRange.Cells[21, col].Value2.ToString();
                                    int lcaId = context.LCAs.SingleOrDefault(x => x.KyHieu == nameLCA).Id;
                                    if (cellValue != 0)
                                    {
                                        NhienLieuSanPham nhienLieuSanPham = new NhienLieuSanPham();
                                        nhienLieuSanPham.SoLuong = cellValue;
                                        nhienLieuSanPham.SanPhamId = idSanPham;
                                        nhienLieuSanPham.LCAId = lcaId;
                                        nhienLieuSanPham.NhienLieuId = NLSP.Id;
                                        nhienLieuSanPham.DonViId = 2;
                                        context.nhienLieuSanPhams.Add(nhienLieuSanPham);
                                        TaoNangLuong.Add(nhienLieuSanPham);
                                    }
                                }
                            }
                            context.SaveChanges();

                            // Khu vực lấy nhiên liệu sản phẩm
                            int startRowNhienLieu = 30;
                            int endRowNhienLieu = 36;
                            List<int> LstNhienLieu = new List<int>();
                            List<NhienLieuSanPham> nhienLlieuSP = new List<NhienLieuSanPham>();
                            for (int row = startRowNhienLieu; row <= endRowNhienLieu; row++)
                            {
                                string nameNL = xlRange.Cells[row, 5].Value2.ToString();
                                NhienLieu NLSP = context.nhienLieus.SingleOrDefault(x => x.TenHienThiTieuThu.ToLower() == nameNL.ToLower());
                                for (int col = startColumnNLN; col <= endColumnNLN; col++)
                                {
                                    //Lấy giá trị
                                    double cellValue = xlRange.Cells[row, col].Value2 != null ? (double)xlRange.Cells[row, col].Value2 : 0;
                                    //Lấy id LCA
                                    string nameLCA = xlRange.Cells[21, col].Value2.ToString();
                                    int lcaId = context.LCAs.SingleOrDefault(x => x.KyHieu == nameLCA).Id;

                                    // Lấy giá trị nameLCA từ danh sách đã lưu
                                    if (cellValue != 0)
                                    {
                                        NhienLieuSanPham nhienLieuSanPham = new NhienLieuSanPham();
                                        nhienLieuSanPham.SoLuong = cellValue;
                                        nhienLieuSanPham.SanPhamId = idSanPham;
                                        nhienLieuSanPham.LCAId = lcaId;
                                        nhienLieuSanPham.NhienLieuId = NLSP.Id;
                                        nhienLieuSanPham.DonViId = 1;
                                        context.nhienLieuSanPhams.Add(nhienLieuSanPham);
                                        context.SaveChanges();
                                        LstNhienLieu.Add(nhienLieuSanPham.Id);
                                        nhienLlieuSP.Add(nhienLieuSanPham);
                                    }
                                }
                            }


                            // Khu vực nước
                            int startRowNuoc = 48;
                            int endRowNuoc = 50;
                            List<NhienLieuSanPham> SDNuoc = new List<NhienLieuSanPham>();
                            for (int row = startRowNuoc; row <= endRowNuoc; row++)
                            {
                                string nameNL = xlRange.Cells[row, 5].Value2.ToString();
                                NhienLieu NLSP = context.nhienLieus.SingleOrDefault(x => x.TenHienThiTieuThu.Trim().ToLower() == nameNL.Trim().ToLower());
                                for (int col = startColumnNLN; col <= endColumnNLN; col++)
                                {
                                    //Lấy giá trị
                                    double cellValue = xlRange.Cells[row, col].Value2 != null ? (double)xlRange.Cells[row, col].Value2 : 0;
                                    //Lấy id LCA
                                    string nameLCA = xlRange.Cells[21, col].Value2.ToString();
                                    int lcaId = context.LCAs.SingleOrDefault(x => x.KyHieu == nameLCA).Id;

                                    // Lấy giá trị nameLCA từ danh sách đã lưu
                                    if (cellValue != 0)
                                    {
                                        NhienLieuSanPham nhienLieuSanPham = new NhienLieuSanPham();
                                        nhienLieuSanPham.SoLuong = cellValue;
                                        nhienLieuSanPham.SanPhamId = idSanPham;
                                        nhienLieuSanPham.LCAId = lcaId;
                                        nhienLieuSanPham.NhienLieuId = NLSP.Id;
                                        nhienLieuSanPham.DonViId = 3;
                                        context.nhienLieuSanPhams.Add(nhienLieuSanPham);
                                        SDNuoc.Add(nhienLieuSanPham);
                                    }
                                }
                            }
                            context.SaveChanges();

                            // Khu vực lấy thải rắn
                            int startRowChatThaiRan = 57;
                            int endRowChatThaiRan = 58;
                            List<ThaiDauRa> chatRan = new List<ThaiDauRa>();
                            for (int row = startRowChatThaiRan; row <= endRowChatThaiRan; row++)
                            {
                                string nameNL = xlRange.Cells[row, 5].Value2.ToString();
                                ChatThai CT = context.chatThais.SingleOrDefault(x => x.TenChatThai.Trim().ToLower() == nameNL.Trim().ToLower());
                                for (int col = startColumnNLN; col <= endColumnNLN; col++)
                                {
                                    //Lấy giá trị
                                    double cellValue = xlRange.Cells[row, col].Value2 != null ? (double)xlRange.Cells[row, col].Value2 : 0;
                                    //Lấy id LCA
                                    string nameLCA = xlRange.Cells[21, col].Value2.ToString();
                                    int lcaId = context.LCAs.SingleOrDefault(x => x.KyHieu == nameLCA).Id;

                                    // Lấy giá trị nameLCA từ danh sách đã lưu
                                    if (cellValue != 0)
                                    {
                                        ThaiDauRa thaiDauRa = new ThaiDauRa();
                                        thaiDauRa.SanPhamId = idSanPham;
                                        thaiDauRa.LCAId = lcaId;
                                        thaiDauRa.ChatThaiId = CT.Id;
                                        thaiDauRa.DonViId = 1;
                                        thaiDauRa.HeSoDieuChinh = 1;
                                        thaiDauRa.SoLuong = cellValue;
                                        context.thaiDauRas.Add(thaiDauRa);
                                        chatRan.Add(thaiDauRa);
                                    }
                                }
                            }
                            context.SaveChanges();


                            // Khu vực lấy nước thải phát sinh
                            int startRowNuocThai = 61;
                            int endRowNuocThai = 68;
                            List<ThaiDauRa> LstPhuDuong = new List<ThaiDauRa>();
                            for (int row = startRowNuocThai; row <= endRowNuocThai; row++)
                            {
                                string nameNuocThai = xlRange.Cells[row, 5].Value2.ToString();
                                ChatThai nuocThai = context.chatThais
                                    .SingleOrDefault(x => x.TenChatThai.ToLower() == nameNuocThai.Trim().ToLower() && x.LoaiChatThaiId == 2);
                                for (int col = startColumnNLN; col <= endColumnNLN; col++)
                                {
                                    //Lấy giá trị
                                    double cellValue = xlRange.Cells[row, col].Value2 != null ? (double)xlRange.Cells[row, col].Value2 : 0;
                                    //Lấy id LCA
                                    string nameLCA = xlRange.Cells[21, col].Value2.ToString();
                                    int lcaId = context.LCAs.SingleOrDefault(x => x.KyHieu == nameLCA).Id;

                                    // Lấy giá trị nameLCA từ danh sách đã lưu
                                    if (cellValue != 0)
                                    {
                                        ThaiDauRa thaiDauRa = new ThaiDauRa();
                                        thaiDauRa.SanPhamId = idSanPham;
                                        thaiDauRa.LCAId = lcaId;
                                        thaiDauRa.SoLuong = cellValue;
                                        thaiDauRa.ChatThaiId = nuocThai.Id;
                                        thaiDauRa.DonViId = 1;
                                        //thaiDauRa.HeSoDieuChinh = 1;
                                        switch (nuocThai.TenChatThai.ToLower())
                                        {
                                            case "cod":
                                                thaiDauRa.HeSoDieuChinh = 0.022;
                                                break;
                                            case "n":
                                                thaiDauRa.HeSoDieuChinh = 0.42;
                                                break;
                                            case "p":
                                                thaiDauRa.HeSoDieuChinh = 3.06;
                                                break;
                                            case "po4":
                                                thaiDauRa.HeSoDieuChinh = 1;
                                                break;
                                            case "nh4":
                                                thaiDauRa.HeSoDieuChinh = 0.33;
                                                break;
                                            case "no":
                                                thaiDauRa.HeSoDieuChinh = 0.2;
                                                break;
                                            case "no2":
                                                thaiDauRa.HeSoDieuChinh = 0.13;
                                                break;
                                            case "nox":
                                                thaiDauRa.HeSoDieuChinh = 0.13;
                                                break;
                                        }
                                        context.thaiDauRas.Add(thaiDauRa);
                                        LstPhuDuong.Add(thaiDauRa);
                                    }
                                }
                            }

                            context.SaveChanges();

                            // Khu vực lấy khí thải phát sinh
                            int startRowKhiThai = 72;
                            int endRowKhiThai = 84;
                            List<ThaiDauRa> LstAxithoa = new List<ThaiDauRa>();
                            for (int row = startRowKhiThai; row <= endRowKhiThai; row++)
                            {
                                string nameKhiThai = xlRange.Cells[row, 5].Value2.ToString();
                                ChatThai khiThai = context.chatThais
                                    .SingleOrDefault(x => x.TenChatThai.ToLower() == nameKhiThai.Trim().ToLower() && x.LoaiChatThaiId == 3);
                                for (int col = startColumnNLN; col <= endColumnNLN; col++)
                                {
                                    //Lấy giá trị
                                    double cellValue = xlRange.Cells[row, col].Value2 != null ? (double)xlRange.Cells[row, col].Value2 : 0;
                                    //Lấy id LCA
                                    string nameLCA = xlRange.Cells[21, col].Value2.ToString();
                                    int lcaId = context.LCAs.SingleOrDefault(x => x.KyHieu == nameLCA).Id;

                                    // Lấy giá trị nameLCA từ danh sách đã lưu
                                    if (cellValue != 0)
                                    {
                                        ThaiDauRa thaiDauRa = new ThaiDauRa();
                                        thaiDauRa.SanPhamId = idSanPham;
                                        thaiDauRa.LCAId = lcaId;
                                        thaiDauRa.SoLuong = cellValue;
                                        thaiDauRa.ChatThaiId = khiThai.Id;
                                        thaiDauRa.DonViId = 1;
                                        //thaiDauRa.HeSoDieuChinh = 0;
                                        switch (khiThai.TenChatThai.ToLower())
                                        {
                                            case "so2":
                                                thaiDauRa.HeSoDieuChinh = 1;
                                                break;
                                            case "nox":
                                                thaiDauRa.HeSoDieuChinh = 0.7;
                                                break;
                                            case "nh3":
                                                thaiDauRa.HeSoDieuChinh = 1.88;
                                                break;
                                            case "no":
                                                thaiDauRa.HeSoDieuChinh = 1.07;
                                                break;
                                            case "no2":
                                                thaiDauRa.HeSoDieuChinh = 0.7;
                                                break;
                                            case "bụi":
                                                thaiDauRa.HeSoDieuChinh = 1;
                                                break;
                                            case "cf2cl2":
                                                thaiDauRa.HeSoDieuChinh = 1;
                                                break;
                                            case "c2f3cl3":
                                                thaiDauRa.HeSoDieuChinh = 1.07;
                                                break;
                                            case "c2f4cl2":
                                                thaiDauRa.HeSoDieuChinh = 0.8;
                                                break;
                                            case "ch4":
                                                thaiDauRa.HeSoDieuChinh = 0.007;
                                                break;
                                            case "cfcl3":
                                                thaiDauRa.HeSoDieuChinh = 1;
                                                break;
                                            case "c2f5cl":
                                                thaiDauRa.HeSoDieuChinh = 0.5;
                                                break;
                                            case "ccl4":
                                                thaiDauRa.HeSoDieuChinh = 1.08;
                                                break;
                                        }
                                        context.thaiDauRas.Add(thaiDauRa);
                                        LstAxithoa.Add(thaiDauRa);
                                    }
                                }
                            }

                            context.SaveChanges();

                            dbTran.Commit();

                            foreach (int item in LstNguyenLieu)
                            {
                                nguyenLieuSanPhamChiSoTacDong.TinhToanChiSo(item);
                            }

                            foreach (int item in LstNhienLieu)
                            {
                                nhienLieuSanPhamChiSoTacDong.TinhToanChiSo(item);
                            }
                            tinhThaiDauRa.KetQuaPhuDuong_Import(LstPhuDuong);
                            tinhAxithoa.KetQuaAxitHoa(LstAxithoa);
                    
                            tinhThaiDauRa.KetQuaPhaHuyOzon_Import(LstAxithoa);
                            tinhThaiDauRa.KetQuaPhatSinhBui_Import(LstAxithoa);
                            tinhThaiDauRa.KetQuaOzonHoa_Import(LstAxithoa);
                            tinhThaiDauRa.GetChatThaiNguyHai_Import(chatRan);

                            tinhThaiDauRa.GetChatThai_Import(chatRan);
                            // tinh cac chi so khac
                            chiSoKhac.KetQuaTaoNL_Import(TaoNangLuong);
                            chiSoKhac.KetQuaSuDungNLTaiTao_Import(nhienLlieuSP);
                            chiSoKhac.KetQuaSuDungNLKoTaiTao_Import(nhienLlieuSP);
                            chiSoKhac.KetQuaSDNuoc_Import(SDNuoc);
                            chiSoKhac.SuDungPTuNLThayThe_Import(nhienLlieuSP);

                            SplashScreenManager.CloseDefaultWaitForm();
                            MessageBox.Show("Thành Công");
                        }
                        catch (Exception ex)
                        {
                            SplashScreenManager.CloseDefaultWaitForm();
                            MessageBox.Show("Thất Bại");
                            dbTran.Rollback();
                        }
                    }
                }
                xlWorkbook.Close();
                xlApp.Quit();
            }
        }
    }
}
